name: wa_sticker
description: "A new Flutter project for AI Sticker Generator"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  

  # Image picker
  image_picker: ^1.2.0

  # Path utilities
  path: ^1.8.3
  path_provider: ^2.0.15

  # Voice recording
  flutter_sound: ^9.3.18
  permission_handler: ^11.3.0

  # UI enhancements
  flutter_spinkit: ^5.1.0

  # State management (optional)
  provider: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
